name: lance_box
description: "A Simple Invoicing Mobile App with OnBoarding"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^2.0.17
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  firebase_app_check: ^0.3.1+4
  firebase_storage: ^12.3.4
  firebase_messaging: ^15.1.3

  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

  custom_lint:
  riverpod_generator: ^2.6.3
  riverpod_lint: ^2.6.3

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/icons/
#    - assets/images/
#    - assets/json/

  fonts:
   - family: Pretendard
     fonts:
       - asset: fonts/Pretendard-Black.otf
       - asset: fonts/Pretendard-Bold.otf
       - asset: fonts/Pretendard-ExtraBold.otf
       - asset: fonts/Pretendard-ExtraLight.otf
       - asset: fonts/Pretendard-Light.ttf
       - asset: fonts/Pretendard-Medium.ttf
       - asset: fonts/Pretendard-Regular.ttf
       - asset: fonts/Pretendard-SemiBold.ttf
       - asset: fonts/Pretendard-Thin.ttf

   - family: PlusJakartaSans
     fonts:
       - asset: fonts/PlusJakartaSans-Italic-VariableFont_wght.ttf
       - asset: fonts/PlusJakartaSans-VariableFont_wght.ttf
